/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author usuario
 */
public class Ejercicio14 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio_14
     */
    public Ejercicio14() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dia1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mes1 = new javax.swing.JTextField();
        año1 = new javax.swing.JTextField();
        dia2 = new javax.swing.JTextField();
        mes2 = new javax.swing.JTextField();
        año2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        j2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        genero = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(dia1);
        dia1.setBounds(22, 64, 75, 29);

        jLabel3.setText("Digite la fecha actual DD/MM/AÑO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(38, 152, 185, 14);

        jLabel2.setText("Digite la fecha de nacimiento DD/MM/AÑO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(22, 32, 230, 14);
        getContentPane().add(mes1);
        mes1.setBounds(115, 64, 75, 28);
        getContentPane().add(año1);
        año1.setBounds(200, 64, 75, 29);
        getContentPane().add(dia2);
        dia2.setBounds(22, 214, 72, 29);
        getContentPane().add(mes2);
        mes2.setBounds(129, 214, 72, 29);
        getContentPane().add(año2);
        año2.setBounds(239, 214, 72, 30);

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(490, 250, 69, 24);

        j2.setColumns(20);
        j2.setRows(5);
        jScrollPane1.setViewportView(j2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(239, 297, 490, 73);

        jLabel1.setText("Digite el genero 1. Hombre 2. Mujer");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(444, 99, 198, 14);
        getContentPane().add(genero);
        genero.setBounds(482, 149, 90, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int a1= Integer.parseInt(año1.getText());
        int a2= Integer.parseInt(año2.getText());
        int m1= Integer.parseInt(mes1.getText());
        int m2= Integer.parseInt(mes2.getText());
        int d1= Integer.parseInt(dia1.getText());
        int d2= Integer.parseInt(dia2.getText());
        int g= Integer.parseInt(genero.getText());
        
       if (validar_fecha(m1, m2,  d1, d2)==1){
           j2.setText("Fecha valida" + " la edad es de: "+ calculo_edad(a1, a2)+ vacunar(g,a1,a2) );
       }
       else{
           j2.setText(""+ "Fecha no valida");
       }
       
    }//GEN-LAST:event_jButton1ActionPerformed
        public static int validar_fecha(int m1, int m2, int d1, int d2){
            
            if(m1>=1 && m1<=12 && m2>=1 && m2<=12  ){
                if((m1==1 && d1>=1 && d1<=31)|| (m1==2 && d1>=1 && d1<=28) || (m1==3 && d1>=1 && d1<=31) ||( m1==4 && d1>=1 && d1<=30) || ( m1==5 && d1>=1 && d1<=31) || ( m1==6 && d1>=1 && d1<=30) ||  (m1==7 && d1>=1 && d1<=31) || (m1==8 && d1>=1 && d1<=31) || (m1==9 && d1>=1 && d1<=30)|| (m1==10 && d1>=1 && d1<=31) || (m1==11 && d1>=1 && d1<=30) || (m1==12 && d1>=1 && d1<=31)){
                    if((m2==1 && d2>=1 && d2<=31)|| (m2==2 && d2>=1 && d2<=28) || (m2==3 && d2>=1 && d2<=31) ||( m2==4 && d2>=1 && d2<=30) || ( m2==5 && d2>=1 && d2<=31) || ( m2==6 && d2>=1 && d2<=30) ||  (m2==7 && d2>=1 && d2<=31) || (m2==8 && d2>=1 && d2<=31) || (m2==9 && d2>=1 && d2<=30)|| (m2==10 && d2>=1 && d2<=31) || (m2==11 && d2>=1 && d2<=30) || (m2==12 && d2>=1 && d2<=31)){
                    return 1;
                    }
                }
            }
          
            return 0;
            
            }
        
        public static int calculo_edad(int  a1, int a2){
            int edad;
            edad=a2-a1;
            return edad;
        }
        public static String vacunar(int g, int a1, int a2){
            
            if(calculo_edad(a1, a2)>=15 && calculo_edad(a1, a2)<18 ){
                if(g==1){
                    String cad=" Vacuna paperas";
                    return cad;
                }
                else{
                    if(g==2){
                    String cad=" Vacuna sarampion";
                    return cad;
                    }
                }
            }
            else{
                    if(calculo_edad(a1, a2)>=18 && calculo_edad(a1, a2)<22 ){
                    if(g==1){
                        String cad=" Vacuna influenza";
                        return cad;
                    }
                    else{
                        if(g==2){
                        String cad=" Vacuna epatitis";
                        return cad;
                        }
                    }
                    }
                    else{
                        if(calculo_edad(a1, a2)>=22 ){
                            String cad=" Vacuna fiebre amarilla";
                            return cad;
                        }
                          else{
                            String cad=" No aplica ninguna vacuna";
                            return cad;
                            }
                    }
            }
        return null;
          
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio14().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField año1;
    private javax.swing.JTextField año2;
    private javax.swing.JTextField dia1;
    private javax.swing.JTextField dia2;
    private javax.swing.JTextField genero;
    private javax.swing.JTextArea j2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mes1;
    private javax.swing.JTextField mes2;
    // End of variables declaration//GEN-END:variables
}
